TK_Basdat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('trigger1/', include('trigger1.urls')),
    path('', include('reservasirs.urls')),
    path('', include('faskes.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('', include('jadwalfaskes.urls'))
]

home/urls.py
from django.urls import path, include
from .views import home

urlpatterns = [
    path('', home),
]

reservasirs/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'reservasirs'

urlpatterns = [
    path('reservasirs/create_reservasi', views.create_reservasi_rs, name='create_form_reservasi_rs'),
    path('reservasirs/list_ruangan', views.get_ruangan, name='list_ruang'),
    path('reservasirs/list_bed', views.get_bed, name='list_bed'),
    path('reservasirs/daftar_reservasi', views.read_reservasi_rs, name='list_reservasi'),
]

reservasirs/models.py
from django.db import models

# Create your models here.

reservasirs/forms.py
from django import forms
from django.db import connection

class CreateReservasiRS (forms.Form):
    def get_all_pasien():
        c = connection.cursor()
        c.execute("set search_path to siruco;")
        c.execute("select nik from pasien;")
        result = c.fetchall()
        c.close()
        return result

    def get_all_koders():
        c = connection.cursor()
        c.execute("set search_path to siruco;")
        c.execute("select kode_faskes from rumah_sakit;")
        result = c.fetchall()
        c.close()
        return result

    nik = forms.ChoiceField(label = "NIK", choices = get_all_pasien())

    tglmasuk = forms.CharField(label='Tanggal Masuk', widget=forms.DateInput(attrs={
        'placeholder': 'Tanggal Masuk',
        }))

    tglkeluar = forms.CharField(label='Tanggal Keluar', widget=forms.DateInput(attrs={
        'placeholder': 'Tanggal Keluar',
        }))
    
    kode_rs = forms.ChoiceField(label="Kode RS", choices= get_all_koders(), required=True)

    kode_ruangan = forms.CharField(label="Kode Ruangan", required = True, widget=forms.Select(choices=[]))

    kode_bed = forms.CharField(label="Kode Bed", required=True, widget=forms.Select(choices=[]))

reservasirs/views.py
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreateReservasiRS
# Create your views here.

def create_reservasi_rs(request):
    response = {}
    response["error"] = False
    form = CreateReservasiRS(request.POST or None) 
    response["form"] = form
    if request.method == "POST":
        if form.is_valid():
            NIK_Pasien = form.cleaned_data['nik']
            tanggal_masuk = request.POST.get('tglmasuk')
            tanggal_keluar = request.POST.get('tglkeluar')
            kode_rs = form.cleaned_data['kode_rs']
            kode_ruangan = form.cleaned_data['kode_ruangan']
            kode_bed = form.cleaned_data['kode_bed']
            
            with connection.cursor() as cursor:
                cursor.execute("insert into reservasi_rs values ('{}','{}','{}','{}','{}','{}');".format(NIK_Pasien,tanggal_masuk, tanggal_keluar, kode_rs, kode_ruangan, kode_bed ))
                return redirect("rumahsakit:list_reservasi")

    form = CreateReservasiRS()
    arguments = {
        'form' : response['form'],
    }
    return render(request, 'createreservasirs.html', arguments)

def get_ruangan(request):
    rumah_sakit = request.GET.get('kode_rs')
    list_ruangan = []

    with connection.cursor() as cursor:
        cursor.execute("select koderuangan from ruangan_rs where koders = '{}' and jmlbed > 0;".format(rumah_sakit))
        list_ruangan = cursor.fetchall()

    daftar_akhir = []
    for i in list_ruangan:
        val = (i[0],i[0])
        daftar_akhir.append(val)
    return render(request, 'listruangan.html', {'listruangan':daftar_akhir})

def get_bed(request):
    rumah_sakit = request.GET.get('kode_rs')
    ruangan = request.GET.get('kode_ruang')
    list_bed = []

    with connection.cursor() as cursor:
        cursor.execute("select kodebed from bed_rs where koders = '{}' and koderuangan = '{}';".format(rumah_sakit,ruangan))
        list_bed = cursor.fetchall()

    final = [] 
    for i in list_bed:
        val = (i[0],i[0])
        final.append(val)
    return render(request, 'listbed.html', {'listbed':final})

def read_reservasi_rs(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco;")
    cursor.execute("select kodepasien, tglmasuk, tglkeluar, koders, koderuangan, kodebed from reservasi_rs;" )
    daftarreservasi = cursor.fetchall()
    arguments = {"daftarreservasi":daftarreservasi}
    return render(request, "daftarreservasi.html", arguments)

reservasirs/templates/createreservasirs.html
<!DOCTYPE html>
<html lang="en">
    <head>
       <title>TKBasdatF2|Reservasi RS/title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Vollkorn">
        <style>
            html,body{
                background: darkslategray;
                font-family:Anton;
                height:100%;
                width: 100%;
            }

            .navbar {
            background:#D199A7;
            }

            .nav-link,
            .navbar-brand {
                color: white;
                cursor: pointer;
            }
                
            .nav-link:hover {
                color: #000;
            }
                
            .navbar-collapse {
                justify-content: flex-end;
            }

            .container-fluid{
                height: 100%;
                width: 100%;
            }

            .mainRow {
                height: 100%;
                width: 100%;
                margin: 0;
            }

            .login{
                text-align:center;
                width:50%;
            }
            
            .login input{
                display:block;
                margin:20px auto;
                text-align:center;
            }
            
            .login input[type="text"],.login input[type="password"]{
                line-height:50px;
                padding:0 10px;
                border-radius:30px;
                border:0;
                width:50%;
                background:antiquewhite;
            }
            
            .header{
                height: 100%;
            }
            
            .login input[type="submit"]{
                height:40px;
                border:0;
                background:black;
                color:#fff;
                width:30%;
                border-radius:5px;
                opacity:0.8;
                cursor:pointer;
            }
            
            .login input[type="submit"]:hover{
                opacity:1;
            }
        </style>
    </head>
    <body class="login_back area" style="height: 100vh;">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light">
            <a class="navbar-brand" style="color:antiquewhite; font-family: Anton" href="/">TKBasdatF2</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav" style="color: antiquewhite; font-family: Anton">
                    <li class="nav-item">
                        <a class="nav-link" href="/reservasirs/daftar_reservasi"><b>reservasi rs</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/faskes/daftar_faskes"><b>faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/jadwalfaskes/list_jadwal"><b>jadwal faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>trigger5</b></a>
                    </li>
                    {% if request.session is not None %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/logout"><b>log out</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/"><b>login</b></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>register</b></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="divider"></div>
            <div class="container-fluid">
                <div class="row mainRow align-items-center justify-content-center">
                    <div class="card-body form_bg_color outer-form container form-column col-md-4">     
                        <h2 style="color:antiquewhite;">Formulir Reservasi RS</h2>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                            <label>NIK Pasien</label> {{ form.nik }}
                            </div>
                            <div class="form-group">
                            <label for="validationDefault01">Tanggal Masuk</label> {{ form.tglmasuk }}
                            </div>
                            <div class="form-group">
                            <label for="validationDefault01">Tanggal Keluar</label> {{ form.tglkeluar }}
                            </div>
                            <div class="form-group">
                            <label for="validationDefault01">Kode Rumah Sakit</label> {{ form.kode_rs }}
                            </div>
                            <div class="form-group">
                            <label for="validationDefault01">Kode Ruangan</label> {{ form.kode_ruangan }}
                            </div>
                            <div class="form-group">
                            <label for="validationDefault01">Kode Bed</label> {{ form.kode_bed }}
                            </div>
                            <input class="btn btn-primary" type="submit" value="submit">
                        </form>    
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script>
        $("#id_kode_rs").change(function(){
            var url = "{% url 'rumahsakit:list_ruang' %}";
            var kode_rs = $(this).val();
            console.log(kode_rs);
            
            $.ajax({
            url: url,
            data: {
                'kode_rs' : kode_rs
            },
            success: function(data) {
                console.log('test')
                console.log(data);
                console.log('test');
                $("#id_kode_ruangan").html(data);
            }
            });
        });  
    </script>
    
    <script>
        $("#id_kode_ruangan").change(function(){
            var url = "{% url 'rumahsakit:list_bed' %}"
            var kode_ruang = $(this).val();
            var kode_rs = $("#id_kode_rs").val();
            console.log(kode_ruang)
            console.log(kode_rs)

            $.ajax({
                url : url,
                data : {
                'kode_rs' : kode_rs,
                'kode_ruang' : kode_ruang
                },
                success: function (data) {
                console.log(data)
                $("#id_kode_bed").html(data);
                }
            });
        });
    </script>
</html>
      

reservasirs/templates/daftarreservasi.html
<!DOCTYPE html>
<html lang="en">
    <head>
       <title>TKBasdatF2|Reservasi RS/title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Vollkorn">
        <style>
            html,body{
                background: darkslategray;
                font-family:Anton;
                height:100%;
                width: 100%;
            }

            .navbar {
            background:#D199A7;
            }

            .nav-link,
            .navbar-brand {
                color: white;
                cursor: pointer;
            }
                
            .nav-link:hover {
                color: #000;
            }
                
            .navbar-collapse {
                justify-content: flex-end;
            }

            .container-fluid{
                height: 100%;
                width: 100%;
            }

            .mainRow {
                height: 100%;
                width: 100%;
                margin: 0;
            }

            .login{
                text-align:center;
                width:50%;
            }
            
            .login input{
                display:block;
                margin:20px auto;
                text-align:center;
            }
            
            .login input[type="text"],.login input[type="password"]{
                line-height:50px;
                padding:0 10px;
                border-radius:30px;
                border:0;
                width:50%;
                background:antiquewhite;
            }
            
            .header{
                height: 100%;
            }
            
            .login input[type="submit"]{
                height:40px;
                border:0;
                background:black;
                color:#fff;
                width:30%;
                border-radius:5px;
                opacity:0.8;
                cursor:pointer;
            }
            
            .login input[type="submit"]:hover{
                opacity:1;
            }
        </style>
    </head>
    <body class="login_back area" style="height: 100vh;">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light">
            <a class="navbar-brand" style="color:antiquewhite; font-family: Anton" href="/">TKBasdatF2</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav" style="color: antiquewhite; font-family: Anton">
                        <li class="nav-item">
                            <a class="nav-link" href="/reservasirs/daftar_reservasi"><b>reservasi rs</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/faskes/daftar_faskes"><b>faskes</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/jadwalfaskes/list_jadwal"><b>jadwal faskes</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/"><b>trigger5</b></a>
                        </li>
                        {% if request.session is not None %}
                        <li class="nav-item">
                            <a class="nav-link" href="/trigger1/logout"><b>log out</b></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/trigger1/"><b>login</b></a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="/"><b>register</b></a>
                        </li>
                    </ul>
                </div>
        </nav>
        <div class="divider"></div>
            <div class="container-fluid">
                <div class="row mainRow align-items-center justify-content-center">
                    <div class="login">      
                        <h2 style="color:antiquewhite;">List Rumah Sakit</h2>
                        <div class="tmargin table-responsive">
                            <table class="table justify-content-center">
                                <thead class="bg-danger text-white align-items-center">
                                    <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">NIK Pasien</th>
                                        <th scope="col">Tanggal Masuk</th>
                                        <th scope="col">Tanggal Keluar</th>
                                        <th scope="col">Rumah Sakit</th>
                                        <th scope="col">Ruangan</th>
                                        <th scope="col">Bed</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  {% for li in daftarreservasi %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{li.0}}</td>
                                        <td>{{li.1}}</td>
                                        <td>{{li.2}}</td>
                                        <td>{{li.3}}</td>
                                        <td>{{li.4}}</td>
                                        <td>{{li.5}}</td>                                                      
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                         
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
      

reservasirs/templates/listbed.html
<option value="">---Pilih Bed---</option>
{% for i in list_bed %}
<option value="{{ i.0 }}">{{ i.1 }}</option>
{% endfor %}

reservasirs/templates/listruangan.html
<option value="">---Pilih Ruangan---</option>
{% for i in list_ruangan %}
<option value="{{ i.0 }}">{{ i.1 }}</option>
{% endfor %}