TK_Basdat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('trigger1/', include('trigger1.urls')),
    path('', include('reservasirs.urls')),
    path('', include('faskes.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('', include('jadwalfaskes.urls'))
]

faskes/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import create_faskes, read_faskes, detail_faskes

app_name = 'faskes'
urlpatterns = [
    path('faskes/create_faskes', create_faskes, name='create_form_faskes'),
    path('faskes/daftar_faskes', read_faskes, name='daftar_faskes'),
    path('faskes/detail_faskes/<str:row>', detail_faskes, name='detail_faskes'),
]

home/urls.py
from django.urls import path, include
from .views import home

urlpatterns = [
    path('', home),
]

faskes/models.py
from django.db import models

# Create your models here.

faskes/forms.py
from django import forms
from django.db import connection

tipeChoices = [('Rumah Sakit','Rumah Sakit'),('Puskesmas','Puskesmas'),('Klinik','Klinik')]

ownerChoices = [('Swasta','Swasta'),('Pemerintah','Pemerintah')]

class CreateFaskes(forms.Form):
    kode =  forms.CharField(label='Kode Faskes', disabled=True, required=True)

    tipe = forms.ChoiceField(label="Tipe", widget = forms.Select(choices = tipeChoices))
    
    nama_faskes = forms.CharField(label='Nama Faskes', widget=forms.TextInput(attrs={
        'placeholder': 'Nama Faskes',
    }))
    
    status_kepemilikan = forms.ChoiceField(label="Status Kepemilikan", widget = forms.Select(choices = ownerChoices)), 
    jalan = forms.CharField(label='Jalan', widget=forms.TextInput(attrs={
        'placeholder': 'Alamat',
    }))

    kelurahan = forms.CharField(label='Kelurahan', widget=forms.TextInput(attrs={
        'placeholder': 'Kelurahan',
    }))

    kecamatan = forms.CharField(label='Kecamatan', widget=forms.TextInput(attrs={
        'placeholder': 'Kecamatan',
    }))

    kabkot = forms.CharField(label='Kabupaten/Kota', widget=forms.TextInput(attrs={
        'placeholder': 'Kabupaten/Kota',
    }))

    provinsi = forms.CharField(label='Provinsi', widget=forms.TextInput(attrs={
        'placeholder': 'Provinsi',
    }))

faskes/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreateFaskes

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    columns = [col[0] for col in desc]
    return[dict(zip(columns, row)) for row in cursor.fetchall()]

def create_faskes(request):
    code = ''
    with connection.cursor() as c:
        c.execute("select count(*) from siruco.faskes")
        num = c.fetchone()
        c.close()
        num_new = num[0]+1
        num_str = str(num_new)
        if num_new < 10:
            code = 'F0'+ num_str
        else :
            code = 'F' + num_str

    initialdict = {"kode" : code}

    response = {}
    response['error'] = False
    form = CreateFaskes(request.POST or None, initial = initialdict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            kode_faskes = form.cleaned_data['kode']
            tipe = request.POST.get('tipe')
            nama_faskes = request.POST.get('nama_faskes')
            status_kepemilikan = request.POST.get('status_kepemilikan')
            jalan = request.POST.get('jalan')
            kelurahan = request.POST.get('kelurahan')
            kecamatan = request.POST.get('kecamatan')
            kabkot = request.POST.get('kabkot')
            provinsi = request.POST.get('provinsi')

            with connection.cursor() as c:
                c.execute("set search_path to siruco")
                c.execute("insert into faskes values ('{}','{}','{}','{}','{}','{}','{}','{}','{}');".format(kode_faskes,tipe,nama_faskes,status_kepemilikan,jalan,kelurahan,kecamatan,kabkot,provinsi))
                return redirect('faskes:list_faskes') 

    form = CreateFaskes()

    arguments = {
        'form' : response['form'],
        'username' : username,
        'password' : password,
        'peran' : peran
    }
    return render(request, 'createfaskes.html', arguments)

    
def read_faskes(request):
    c = connection.cursor()
    c.execute('set search_path to siruco')
    c.execute('select kode, nama, tipe from faskes')
    list_faskes = namedtuplefetchall(c)
    return render(request, 'daftarfaskes.html', {'list_faskes': list_faskes})

def detail_faskes(request, row):
    c = connection.cursor()
    c.execute('set search_path to siruco')
    c.execute('select * from faskes where kode = %s;',[row])
    datafaskes = namedtuplefetchall(c)
    response = {}
    response['kode'] = datafaskes[0]
    response['tipe'] = datafaskes[1]
    response['nama'] = datafaskes[2]
    response['status_kepemilikan'] = datafaskes[3]
    response['jalan'] = datafaskes[4]
    response['kelurahan'] = datafaskes[5]
    response['kecamatan'] = datafaskes[6]
    response['kabkot'] = datafaskes[7]
    response['provinsi'] = datafaskes[8]
    c.close()
    return render(request, 'detailfaskes.html', response)

faskes/templates/createfaskes.html
<!DOCTYPE html>
<html lang="en">
    <head>
       <title>TKBasdatF2|FasKes/title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Vollkorn">
        <style>
            html,body{
                background: darkslategray;
                font-family:Anton;
                height:100%;
                width: 100%;
            }

            .navbar {
            background:#D199A7;
            }

            .nav-link,
            .navbar-brand {
                color: white;
                cursor: pointer;
            }
                
            .nav-link:hover {
                color: #000;
            }
                
            .navbar-collapse {
                justify-content: flex-end;
            }

            .container-fluid{
                height: 100%;
                width: 100%;
            }

            .mainRow {
                height: 100%;
                width: 100%;
                margin: 0;
            }

            .login{
                text-align:center;
                width:50%;
            }
            
            .login input{
                display:block;
                margin:20px auto;
                text-align:center;
            }
            
            .login input[type="text"],.login input[type="password"]{
                line-height:50px;
                padding:0 10px;
                border-radius:30px;
                border:0;
                width:50%;
                background:antiquewhite;
            }
            
            .header{
                height: 100%;
            }
            
            .login input[type="submit"]{
                height:40px;
                border:0;
                background:black;
                color:#fff;
                width:30%;
                border-radius:5px;
                opacity:0.8;
                cursor:pointer;
            }
            
            .login input[type="submit"]:hover{
                opacity:1;
            }
        </style>
    </head>
    <body class="login_back area" style="height: 100vh;">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light">
            <a class="navbar-brand" style="color:antiquewhite; font-family: Anton" href="/">TKBasdatF2</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav" style="color: antiquewhite; font-family: Anton">
                    <li class="nav-item">
                        <a class="nav-link" href="/reservasirs/daftar_reservasi"><b>reservasi rs</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/faskes/daftar_faskes"><b>faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/jadwalfaskes/list_jadwal"><b>jadwal faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>trigger5</b></a>
                    </li>
                    {% if request.session is not None %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/logout"><b>log out</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/"><b>login</b></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>register</b></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="divider"></div>
            <div class="container-fluid">
                <div class="row mainRow align-items-center justify-content-center">
                    <div class="card-body form_bg_color outer-form container form-column col-md-4">     
                        <h2 style="color:antiquewhite;">Formulir Reservasi RS</h2>
                        <form action="{% url 'faskes:create_form_faskes' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                              <label for="validationDefault01">Kode Faskes</label> {{ form.kode }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Tipe</label> {{ form.tipe }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Nama Faskes</label> {{ form.nama_faskes }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Status Kepemilikan</label> {{ form.status_kepemilikan }}
                            </div>
                            <h3>Alamat :</h3>
                            <br>
                            <div class="form-group">
                              <label for="validationDefault01">Jalan</label> {{ form.jalan }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Kelurahan</label> {{ form.kelurahan }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Kecamatan</label> {{ form.kecamatan }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Kabupaten/Kota</label> {{ form.kabkot }}
                            </div>
                            <div class="form-group">
                              <label for="validationDefault01">Provinsi</label> {{ form.provinsi }}
                            </div>
                            <input class="btn btn-primary" type="submit" value="SIMPAN">
                        </form>                     
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
      

faskes/templates/daftarfaskes.html
<!DOCTYPE html>
<html lang="en">
    <head>
       <title>TKBasdatF2|FasKes/title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Vollkorn">
        <style>
            html,body{
                background: darkslategray;
                font-family:Anton;
                height:100%;
                width: 100%;
            }

            .navbar {
            background:#D199A7;
            }

            .nav-link,
            .navbar-brand {
                color: white;
                cursor: pointer;
            }
                
            .nav-link:hover {
                color: #000;
            }
                
            .navbar-collapse {
                justify-content: flex-end;
            }

            .container-fluid{
                height: 100%;
                width: 100%;
            }

            .mainRow {
                height: 100%;
                width: 100%;
                margin: 0;
            }

            .login{
                text-align:center;
                width:50%;
            }
            
            .login input{
                display:block;
                margin:20px auto;
                text-align:center;
            }
            
            .login input[type="text"],.login input[type="password"]{
                line-height:50px;
                padding:0 10px;
                border-radius:30px;
                border:0;
                width:50%;
                background:antiquewhite;
            }
            
            .header{
                height: 100%;
            }
            
            .login input[type="submit"]{
                height:40px;
                border:0;
                background:black;
                color:#fff;
                width:30%;
                border-radius:5px;
                opacity:0.8;
                cursor:pointer;
            }
            
            .login input[type="submit"]:hover{
                opacity:1;
            }
        </style>
    </head>
    <body class="login_back area" style="height: 100vh;">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light">
            <a class="navbar-brand" style="color:antiquewhite; font-family: Anton" href="/">TKBasdatF2</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav" style="color: antiquewhite; font-family: Anton">
                    <li class="nav-item">
                        <a class="nav-link" href="/reservasirs/daftar_reservasi"><b>reservasi rs</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/faskes/daftar_faskes"><b>faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/jadwalfaskes/list_jadwal"><b>jadwal faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>trigger5</b></a>
                    </li>
                    {% if request.session is not None %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/logout"><b>log out</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/"><b>login</b></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>register</b></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="divider"></div>
            <div class="container-fluid">
                <div class="row mainRow align-items-center justify-content-center">
                    <div class="login">      
                        <h2 style="color:antiquewhite;">List Fasilitas Kesehatan</h2>
                        <div class="tmargin table-responsive">
                            <table class="table justify-content-center">
                                <thead class="bg-danger text-white align-items-center">
                                    <tr>
                                        <th scope="col">Kode Faskes</th>
                                        <th scope="col">Tipe</th>
                                        <th scope="col">Nama Faskes</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for i in hasil %}
                                    <tr>
                                        <td>{{li.kode}}</td>
                                        <td>{{li.tipe}}</td>
                                        <td>{{li.nama}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
      

faskes/templates/detailfaskes.html
<!DOCTYPE html>
<html lang="en">
    <head>
       <title>TKBasdatF2|Reservasi RS/title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Vollkorn">
        <style>
            html,body{
                background: darkslategray;
                font-family:Anton;
                height:100%;
                width: 100%;
            }

            .navbar {
            background:#D199A7;
            }

            .nav-link,
            .navbar-brand {
                color: white;
                cursor: pointer;
            }
                
            .nav-link:hover {
                color: #000;
            }
                
            .navbar-collapse {
                justify-content: flex-end;
            }

            .container-fluid{
                height: 100%;
                width: 100%;
            }

            .mainRow {
                height: 100%;
                width: 100%;
                margin: 0;
            }

            .login{
                text-align:center;
                width:50%;
            }
            
            .login input{
                display:block;
                margin:20px auto;
                text-align:center;
            }
            
            .login input[type="text"],.login input[type="password"]{
                line-height:50px;
                padding:0 10px;
                border-radius:30px;
                border:0;
                width:50%;
                background:antiquewhite;
            }
            
            .header{
                height: 100%;
            }
            
            .login input[type="submit"]{
                height:40px;
                border:0;
                background:black;
                color:#fff;
                width:30%;
                border-radius:5px;
                opacity:0.8;
                cursor:pointer;
            }
            
            .login input[type="submit"]:hover{
                opacity:1;
            }
        </style>
    </head>
    <body class="login_back area" style="height: 100vh;">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light">
            <a class="navbar-brand" style="color:antiquewhite; font-family: Anton" href="/">TKBasdatF2</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav" style="color: antiquewhite; font-family: Anton">
                    <li class="nav-item">
                        <a class="nav-link" href="/reservasirs/daftar_reservasi"><b>reservasi rs</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/faskes/daftar_faskes"><b>faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/jadwalfaskes/list_jadwal"><b>jadwal faskes</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>trigger5</b></a>
                    </li>
                    {% if request.session is not None %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/logout"><b>log out</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/trigger1/"><b>login</b></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>register</b></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container px-4 px-lg-5 mt-5">
            <div class="card">
                <h5>Kode Faskes: {{kode}}</h5>
                <h5>Tipe: {{tipe}}</h5>
                <h5>Nama Faskes: {{nama}}</h5>
                <h5>Status: {{status_kepemilikan}}</h5>
                <br>
                <h5>Alamat:</h5>
                <h5>Jalan: {{jalan}}</h5>
                <h5>Kelurahan: {{kelurahan}}</h5>
                <h5>Kecamatan: {{kecamatan}}</h5>
                <h5>Kabupaten/Kota: {{kabkot}}</h5>
                <h5>Provinsi: {{provinsi}}</h5>
            </div>
        </div>        
    </body>
</html>
      